"""
Preliminary system-size guidance.

READ THIS BEFORE CHANGING ANYTHING HERE.

The original Econ and Shelly notebooks contain no sizing rule. `PPV` is a list
of candidate sizes typed in by the engineer; nothing in the code selects one.
What the notebooks do compute, per candidate size, is:

    PV max kWh/year      the ceiling: irradiance x kWp x EtaPV, integrated
    PV direct kWh/year   the part actually consumed on site, after calc_PVact
    PV direct share %    PV direct / PV max     -- how much of the array is used
    PV maximum share %   PV max / consumption   -- how much of the load is covered

This module does not invent a rule. It ranks the sizes the user entered
against those two existing numbers, explains each ranking in plain language,
and states what an engineer still has to decide. The thresholds below are
PLACEHOLDERS with no engineering authority. Until Equator Solar sets them,
every output of this module is labelled preliminary.

What is still needed from engineering, and why it cannot be guessed here:
  * the acceptable floor for direct-use share (inverter clipping, export
    rules, whether a battery is in scope)
  * the target for share of load covered (commercial, not technical)
  * roof or ground area available, and its orientation
  * inverter and transformer limits at the site
  * the tariff, capital cost and payback horizon
  * whether the measured period is representative of the year
"""

from __future__ import annotations

from dataclasses import dataclass, field

import pandas as pd

from . import config as cfg

# ---------------------------------------------------------------------------
# PLACEHOLDER THRESHOLDS -- not approved engineering values
# ---------------------------------------------------------------------------

#: Below this direct-use share, an array is judged to be generating more than
#: the site can absorb during the day. Placeholder.
MIN_DIRECT_SHARE_PCT = 85.0

#: Above this share of annual consumption, the array is judged large relative
#: to the load. Placeholder.
MAX_LOAD_SHARE_PCT = 60.0

#: Set True once engineering has agreed the numbers above, so the app can drop
#: the "placeholder" wording. Leave False until then.
THRESHOLDS_APPROVED = False


@dataclass
class SizeAssessment:
    """One candidate size, with the numbers behind it kept separate."""

    kwp: float
    pv_max_kwh_year: float = 0.0          # from data + assumptions
    pv_direct_kwh_year: float = 0.0       # from data + assumptions
    direct_share_pct: float = 0.0         # from data + assumptions
    load_share_pct: float = 0.0           # from data + assumptions
    verdict: str = ""                     # generated by this module
    reasons: list = field(default_factory=list)


@dataclass
class SizingResult:
    consumption_kwh_year: float = 0.0
    assessments: list = field(default_factory=list)
    preferred_kwp: float | None = None
    measured_inputs: dict = field(default_factory=dict)
    user_assumptions: dict = field(default_factory=dict)
    caveats: list = field(default_factory=list)
    approved: bool = False

    @property
    def table(self) -> pd.DataFrame:
        rows = []
        for a in self.assessments:
            rows.append({
                "Size [kWp]": a.kwp,
                "PV max [kWh/yr]": round(a.pv_max_kwh_year),
                "PV used on site [kWh/yr]": round(a.pv_direct_kwh_year),
                "Used on site [%]": round(a.direct_share_pct, 1),
                "Share of load [%]": round(a.load_share_pct, 1),
                "Assessment": a.verdict,
            })
        return pd.DataFrame(rows)


def _reason_for(a: SizeAssessment) -> tuple:
    """Verdict and plain-language reasons for one candidate."""
    reasons = []

    if a.direct_share_pct >= MIN_DIRECT_SHARE_PCT:
        reasons.append(
            "%.0f%% of what this array would generate is used on site, so "
            "little is wasted." % a.direct_share_pct)
    else:
        reasons.append(
            "Only %.0f%% of what this array would generate is used on site. "
            "The rest has nowhere to go unless it is exported or stored."
            % a.direct_share_pct)

    if a.load_share_pct <= MAX_LOAD_SHARE_PCT:
        reasons.append(
            "It covers %.0f%% of the year's electricity, leaving the grid to "
            "carry the rest." % a.load_share_pct)
    else:
        reasons.append(
            "It covers %.0f%% of the year's electricity, which is a large "
            "share for a system without storage." % a.load_share_pct)

    fits_direct = a.direct_share_pct >= MIN_DIRECT_SHARE_PCT
    fits_load = a.load_share_pct <= MAX_LOAD_SHARE_PCT
    if fits_direct and fits_load:
        verdict = "Within both placeholder thresholds"
    elif fits_direct:
        verdict = "Large relative to the load"
    elif fits_load:
        verdict = "Generation exceeds daytime demand"
    else:
        verdict = "Outside both placeholder thresholds"
    return verdict, reasons


def assess(dfPVd: pd.DataFrame, ppv, validation=None,
           eta_pv: float = 0.8, offset: float = 0.0) -> SizingResult:
    """Rank candidate sizes using only figures the existing code produces.

    dfPVd is summary_yield's output: rows 'Consumption kWh/year',
    'PV max kWh/year', 'PV direct kWh/year', 'PV direct share %',
    'PV maximum share %', one column per size labelled '<n> kWp'.
    """
    result = SizingResult(approved=THRESHOLDS_APPROVED)

    if dfPVd is None or dfPVd.empty:
        result.caveats.append(
            "The PV yield summary is empty, so no sizes could be assessed.")
        return result

    for size in ppv:
        col = "%s kWp" % size
        if col not in dfPVd.columns:
            continue
        a = SizeAssessment(kwp=float(size))
        a.pv_max_kwh_year = float(dfPVd.at["PV max kWh/year", col])
        a.pv_direct_kwh_year = float(dfPVd.at["PV direct kWh/year", col])
        a.direct_share_pct = float(dfPVd.at["PV direct share %", col])
        a.load_share_pct = float(dfPVd.at["PV maximum share %", col])
        a.verdict, a.reasons = _reason_for(a)
        result.assessments.append(a)

    if "Consumption kWh/year" in dfPVd.index and len(dfPVd.columns):
        result.consumption_kwh_year = float(
            dfPVd.at["Consumption kWh/year", dfPVd.columns[0]])

    # Preferred candidate: the largest that stays inside both placeholder
    # thresholds. If none does, the one with the highest direct-use share.
    inside = [a for a in result.assessments
              if a.direct_share_pct >= MIN_DIRECT_SHARE_PCT
              and a.load_share_pct <= MAX_LOAD_SHARE_PCT]
    if inside:
        result.preferred_kwp = max(inside, key=lambda a: a.kwp).kwp
    elif result.assessments:
        result.preferred_kwp = max(
            result.assessments, key=lambda a: a.direct_share_pct).kwp

    # --- keep the three kinds of number apart, as the brief requires -----
    result.measured_inputs = {
        "Annual consumption [kWh]": round(result.consumption_kwh_year),
    }
    result.user_assumptions = {
        "System efficiency EtaPV": eta_pv,
        "Generation offset": offset,
        "Candidate sizes [kWp]": ", ".join(str(s) for s in ppv),
        "Irradiation profile": "the uploaded irradiation CSV",
    }

    if validation is not None:
        result.measured_inputs["Measurement period [days]"] = round(
            validation.span_days, 1)
        result.measured_inputs["Period actually recorded [%]"] = round(
            100 * validation.overall_coverage, 1)
        if validation.overall_coverage < cfg.MIN_OVERALL_COVERAGE:
            result.caveats.append(
                "Only %.0f%% of the measurement period was recorded. The "
                "consumption figure these sizes are ranked against is an "
                "average over the data that exists, not over the whole "
                "period." % (100 * validation.overall_coverage))
        for window in validation.unmeasured_windows:
            result.caveats.append(
                "The %s window was barely measured, so the daily load shape "
                "used in the simulation is incomplete. Direct-use share is "
                "unreliable for every size below." % window)
        if validation.span_days < 7:
            result.caveats.append(
                "The measurement covers %.1f days. A week or more is needed "
                "before a load shape can be called typical."
                % validation.span_days)

    result.caveats.append(
        "Seasonal variation is not modelled: one irradiation day profile is "
        "applied to all 365 days, as in the original analysis.")
    if not THRESHOLDS_APPROVED:
        result.caveats.append(
            "The thresholds used to rank these sizes (%.0f%% minimum "
            "direct use, %.0f%% maximum share of load) are placeholders with "
            "no engineering authority. They are in src/sizing.py and must be "
            "set by Equator Solar before this ranking means anything."
            % (MIN_DIRECT_SHARE_PCT, MAX_LOAD_SHARE_PCT))
    result.caveats.append(
        "Roof area, orientation, inverter and transformer limits, tariff and "
        "payback are not considered anywhere in this tool.")

    return result


def headline(result: SizingResult) -> str:
    """One sentence for the top of the recommendation section."""
    if result.preferred_kwp is None:
        return ("No candidate size could be assessed from this data.")
    status = "" if result.approved else " (preliminary, placeholder thresholds)"
    return ("Of the sizes entered, %g kWp ranks highest against the two "
            "measures the existing analysis produces%s. This is not a system "
            "size and requires engineering review."
            % (result.preferred_kwp, status))
